name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        node-version: [20.11.1]

    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{vars.DEBUG}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASS: ${{secrets.DB_PASS}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set virtual environment
        run: |
          python3.11 -m venv venv
          source ${{secrets.VENV_PATH}}/venv/bin/activate
      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
          echo "DEBUG=${{vars.DEBUG}}" >> .env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
          echo "DB_USER=${{secrets.DB_USER}}" >> .env
          echo "DB_PASS=${{secrets.DB_PASS}}" >> .env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: Migrate Database
        run: python manage.py migrate --no-input
      - name: Collect static
        run: python manage.py collectstatic --no-input
      - name: Rerun server
        run: /home/perak/.nvm/versions/node/v${{matrix.node-version}}/bin/pm2 restart pacilflix_api --update-env
